# Generated by Django 5.0.7 on 2025-01-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
