# Generated by Django 5.0.7 on 2025-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='opening_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
